# Site settings
title: melanie tosik
description: NLP/ML research engineer and MSCS student at NYU.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.melanietosik.com/" # the base hostname & protocol for your site, e.g. http://example.com
repository: melanietosik/melanietosik.github.io

github_username: melanietosik
medium_username: melanietosik

social_link: twitter
social_username: meltomene

theme_color: white

# Build settings
markdown: kramdown
