title:            "Melanie Tosik"
description:      "NLP and computer science"
url:              http://www.melanietosik.com
signoff:          "Melanie"
share:            false

links:
  - name:         About me
    url:          /
    external:     false
  - name:         Portfolio
    url:          /portfolio
    external:     false

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
